### ISSUE TITLE
Unable to resolve action BlenderKit/blender-addon-build-action, repository not found

### ISSUE THREAD

**Issue by atticus-lv** [BlenderKit/blender-addon-build#1]
```
jobs:
  # This workflow contains a single job called "greet"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Build Blender Addon
      uses: BlenderKit/blender-addon-build-action@v1
      with:
        name: 'PolyQuilt'
        name-suffix: 'commit-hash'
        build-command: 'make build'
        build-location: './Addons/PolyQuilt'
        do-checkout: 'true'
        exclude-files: '.git;.github;.gitignore'
```
